// ...existing code...
using SAFE.Server.Services;

public class Startup
{
    // ...existing code...
    public void ConfigureServices(IServiceCollection services)
    {
        // ...existing code...
        services.AddScoped<NotificationService>();
        // ...existing code...
    }
    // ...existing code...
}
// ...existing code...
